### ISSUE TITLE
Webpacker has been retired / Upgrade frontend bundling

### ISSUE THREAD

**Issue by Splines** [MaMpf-HD/mampf#454]
From the Webpacker [Readme](https://github.com/rails/webpacker):

> Webpacker has served the Rails community for over five years as a bridge to compiled and bundled JavaScript. This bridge is no longer needed for most people in most situations following [the release of Rails 7](https://rubyonrails.org/2021/12/15/Rails-7-fulfilling-a-vision). We now have [three great default answers to JavaScript in 2021+](https://world.hey.com/dhh/rails-7-will-have-three-great-answers-to-javascript-in-2021-8d68191b), and thus we will no longer be evolving Webpacker in an official Rails capacity.

> Finally, you can continue to use Webpacker as-is. We will continue to address security issues on the Ruby side of the gem according to [the normal maintenance schedule of Rails](https://guides.rubyonrails.org/maintenance_policy.html#security-issues). But we will not be updating the gem to include newer versions of the JavaScript libraries. This pertains to the v5 edition of this gem that was included by default with previous versions of Rails.

So, while we can except some more security updates in the short term, we should definitely **adopt one of Rails 7 ["new answers to JavaScript"](https://world.hey.com/dhh/rails-7-will-have-three-great-answers-to-javascript-in-2021-8d68191b) in the long run**, to still get security updates (in the distant future) and also new JS features.

> So that's the story for JavaScript in Rails 7 and beyond. A default path with Hotwire and import maps, an alternate path using a thin integration with one of the popular JavaScript bundlers. [...]

## A quote on the old Asset Pipeline (Sprockets) vs. new approaches

> "The problem with Sprockets (the old assets pipeline) is that it did not integrate with front-end package distribution systems like NPM or Yarn and relied on the community to make gemified versions of these packages. If you wanted to use something that was not available as a gem you would have to download it manually or integrate Webpack or some other package manager anyways. It was pretty great back when rails was one of the only frameworks to ship with an assets pipeline but is completely obsolete today." ~ from [here](https://stackoverflow.com/questions/64197591/webpack-vs-asset-pipeline-in-rails-6)

## Further resources
- [Rails 7 will have three great answers to JavaScript in 2021+](https://world.hey.com/dhh/rails-7-will-have-three-great-answers-to-javascript-in-2021-8d68191b)
- [Rails 7 replaces Webpacker with importmapped Hotwire as default JavaScript setup](https://blog.saeloun.com/2021/11/16/replacing-webpacker-with-importmapped)
- [Thinking in Hotwire: Progressive Enhancement](https://boringrails.com/articles/thinking-in-hotwire-progressive-enhancement/) - This has some really great examples of what Hotwire is all about
- [Rails and JavaScript, Part 5](https://noelrappin.com/blog/2021/09/rails-7-and-javascript/)

---

### New list

- [`Procfile.dev`, `bin/dev` blogpost](https://railsnotes.xyz/blog/procfile-bin-dev-rails7)
- [Rails detailed update guide](https://github.com/rails/propshaft/blob/main/UPGRADING.md)
- [Overview: Asset Pipeline](https://guides.rubyonrails.org/asset_pipeline.html)
- [Migration to Vite Ruby](https://vite-ruby.netlify.app/guide/migration.html#migrating-to-vite)
- [Rails 8 assets: Break down of how Propshaft and importmap-rails work together](https://radanskoric.com/articles/rails-assets-propshaft-importmaps)
- [Why do we still need bundlers?](https://rolldown.rs/guide/in-depth/why-bundlers#why-do-we-still-need-bundlers)
- [Relationship: Vite & Propshaft](https://github.com/ElMassimo/vite_ruby/discussions/539#discussioncomment-13426856)
- [CoffeeScript](https://github.com/ElMassimo/vite_ruby/discussions/559)
- [Working with JS in Rails](https://railsdocs.org/guides/digging_deeper/working_with_javascript_in_rails)

**Comment by Splines** [comment]
We should consider #421 alongside this.

**Comment by Splines** [comment]
Also consider the role of the `sprockets` asset packing library along the way and its interplay with webpacker. This already feels like it's going to be a big pain to migrate to the new Rails way of managing JS assets. However, it will probably help to streamline things and tidy up the frontend files we have right now (and getting rid of `.coffee`).

**Comment by Splines** [comment]
We should also consider the bug https://github.com/MaMpf-HD/mampf/pull/468. Maybe, we can manage `.css` files, so they are really only applied to the partials etc. and not mingled together into one big bundle that gets applied to the whole page. That is, we should be able to use something like `li { ... }` in css and only affect the list items in the views that import the respective stylesheet and *not* every list item on *any* view.

**Comment by fosterfarrell9** [comment]
Let me just say in defense of the global bundling by sprockets that we use a lot of nested partials (I would guess that a "nesting level" of 5 or 6 is not uncommon), and a lot of partials are used in different contexts. I would imagine that with local styling, it could be quite challenging to keep track of what the css rules are in a given view.

**Comment by Splines** [comment]
@fosterfarrell9 Ok true, that might really be challenging, especially for all the already existing files. So, it'd be probably easier to continue using explicit CSS, e.g. `#my-super-cool-div-wrapping-things .li { ... }` etc.

**Comment by Splines** [comment]
Note: Also try to switch to another datetimepicker or import it in a more canonical way instead of the dirty and fragile hacks in `application.js`.

**Comment by Splines** [comment]
Getting rid of `webpacker` does not necessarily mean we have to replace it by `webpack` (without the _er_ at the end). While `webpack` was for a long time the only way to bundle for the web, we now have a plethora of options to choose from. Those are often faster than webpack: for JS files it's not a too big issue for us, but the workflow with SCSS files is really bad right now as you have to wait almost a minute (didn't measure but estimated) before the SCSS is finally bundled to see the changes.

For some alternative bundling tools, see for example [this article](https://blixtdev.com/you-dont-need-webpack-3-better-alternatives-for-building-your-javascript/). While I haven't used it yet, I've heard about [**Vite**](https://vite.dev/) many times on the Internet. And with almost 68K GitHub stars, it's not unknown ;) It even has its own [Vite Ruby](https://vite-ruby.netlify.app/guide/introduction.html#why-vite-%F0%9F%A4%94) off-spring, see also the [Introduction](https://vite-ruby.netlify.app/guide/introduction.html#why-vite-%F0%9F%A4%94) and the available [Rails Integration](https://vite-ruby.netlify.app/guide/rails.html). It might be worth to check out. We just have to see if our custom webpack config can be ported to it.

**Comment by Splines** [comment]
In the new setup, we could also use minification and obfuscation to greatly shrink the frontend bundle sizes. Additionally, we could get rid of properties like `data-cy` for the frontend.

**Comment by Splines** [comment]
With Rails 8.0 (see #710), we could think about Propshaft + Vite together.

**Comment by Splines** [comment]
With regards to SASS/SCSS, we currently get the following deprecation warning

> DEPRECATION WARNING [legacy-js-api]: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
More info: https://sass-lang.com/d/legacy-js-api

In a setup with Vite, we could use [this solution](https://github.com/sass/dart-sass/issues/2352#issuecomment-2358290696).

**Comment by Splines** [comment]
### TODOs

Note that many things that are already done are not listed here.

- [x] Replace [tag helpers](https://vite-ruby.netlify.app/guide/rails.html#tag-helpers-%F0%9F%8F%B7) with Vite ones
- [ ] ~~[Revise general Frontend-folder structure](https://github.com/ElMassimo/vite_ruby/discussions/564) -> this is something for longer-term~~
- [ ] Check js-routes gem (was compiled in `bin/webpack-dev-server` beforehand, also checkout [JS From Routes](https://js-from-routes.netlify.app/) as alternative
- [ ] Vite Plugin ERB? [see here](https://github.com/ElMassimo/vite-plugin-erb?tab=readme-ov-file) -> but why discouraged? [See my issue here](https://github.com/ElMassimo/vite-plugin-erb/issues/6)
- [ ] devise bootstrap forms?
- [ ] Remove/Rework `config/initializers/assets.rb`
- [ ] Use npm deps for dependencies in `_head.html.erb`
- [x] [Setup jquery with vite](https://dev.to/chmich/setup-jquery-on-vite-598k)
- [x] Coffeescript, see [here](https://github.com/ElMassimo/vite_ruby/discussions/559)
- [ ] Reference stylesheets in ActionMailer
- [ ] What to do with Commontator? See [this issue](https://github.com/lml/commontator/issues/197)
- [ ] Remove Turoblinks and setup Turbo, see [here](https://dev.to/chmich/setup-turbo-on-vite-4j8i) and [Migration Guide](https://github.com/hotwired/turbo-rails/blob/main/UPGRADING.md)
- [ ] Might want to get rid of [bootstrap_form gem](https://github.com/bootstrap-ruby/bootstrap_form)
- [ ] Work through [deployment section](https://vite-ruby.netlify.app/guide/deployment.html)
- [ ] Compile using vite also in production
- [ ] Vite in Docker, [post](https://evilmartians.com/chronicles/vite-lizing-rails-get-live-reload-and-hot-replacement-with-vite-ruby) and [repo](https://github.com/ElMassimo/vite_rails_docker_example?tab=readme-ov-file)
- [ ] Pain Point: CSS delayed loading (due to lazy-load). Also see https://github.com/vitejs/vite/issues/16515
- [ ] SASS legacy API [see fix](https://github.com/sass/dart-sass/issues/2352#issuecomment-2358290696)
